### PR TITLE
Don't use PyUnicode_New in pypy3

### LINKED ISSUE #17: Support for PyPy3
This is a tracking issue for PyPy3 support.

Currently, the missing component is `PyUnicode_New`. I posted that issue to the pypy project:

https://bitbucket.org/pypy/pypy/issues/2723/undefined-symbol-pyunicode_new-in-pypy3

### PR DESCRIPTION
**Pull request by jameshilliard**
Should fix #17.

### CODE REVIEW

**Comment by jameshilliard** [comment]
@tiran could you possibly do another release with this change included?

**Comment by imachug** [comment]
@tiran Any reason why this PR isn't merged?

**Comment by jameshilliard** [comment]
@tiran Could you take a look at this? This library is blocking pypy compatibility for a number of other libraries since it's a dependency for them.

**Comment by jameshilliard** [comment]
Hmm, just checked again and seems this may not be needed for newer pypy versions since [this commit](https://foss.heptapod.net/pypy/pypy/commit/ed115224618ab871c2048cb5e7860aba161b3948).

**Comment by tiran** [comment]
pysha3 is no longer supported. Please use SHA-3 from Python's hashlib module.

**Pull request closed without merging**
